---
# Flat File to Ansible Inventory Converter
# Produces host metadata only - credentials handled by AAP2

- name: Convert Flat File to Inventory
  hosts: localhost
  gather_facts: no
  vars:
    input_file: "{{ flatfile_input | default('databases.txt') }}"
    output_file: "{{ inventory_output | default('inventory.yml') }}"

    # Simple inventory structure
    inventory_data:
      all:
        children:
          mssql_databases:
            hosts: {}
          oracle_databases:
            hosts: {}
          sybase_databases:
            hosts: {}

    platform_counts:
      mssql: 0
      oracle: 0
      sybase: 0

  tasks:
    - name: Check input file exists
      stat:
        path: "{{ input_file }}"
      register: input_stat

    - name: Fail if input file missing
      fail:
        msg: "Input file not found: {{ input_file }}"
      when: not input_stat.stat.exists

    - name: Read flat file
      slurp:
        src: "{{ input_file }}"
      register: flat_file

    - name: Parse lines
      set_fact:
        lines: "{{ (flat_file.content | b64decode).split('\n') }}"

    - name: Process each line
      include_tasks: process_flatfile_line.yml
      loop: "{{ lines }}"
      loop_control:
        index_var: idx
        label: "Line {{ idx + 1 }}"
      when:
        - item | trim | length > 0
        - not item.strip().startswith('#')

    - name: Write inventory file
      copy:
        content: "{{ inventory_data | to_nice_yaml }}"
        dest: "{{ output_file }}"

    - name: Summary
      debug:
        msg: |
          Conversion complete: {{ output_file }}
          - MSSQL: {{ platform_counts.mssql }} hosts
          - Oracle: {{ platform_counts.oracle }} hosts
          - Sybase: {{ platform_counts.sybase }} hosts
          - Total: {{ platform_counts.mssql + platform_counts.oracle + platform_counts.sybase }} hosts
