---
# Staging Inventory - Database Compliance Scanning
# For testing before production deployment

all:
  children:
    mssql_databases:
      hosts:
        # Add staging MSSQL servers here
        # SQLSTG01_1433:
        #   mssql_server: sqlstg01.example.com
        #   mssql_port: 1433
        #   mssql_version: "2019"
      vars:
        mssql_username: nist_scan_user
        inspec_delegate_host: ""
        inspec_results_dir: /tmp/inspec_mssql_results
        inspec_debug_mode: true  # Enable debug for staging

    oracle_databases:
      hosts:
        # Add staging Oracle databases here
      vars:
        oracle_username: nist_scan_user
        inspec_delegate_host: ""

    sybase_databases:
      hosts:
        # Add staging Sybase databases here
      vars:
        sybase_username: nist_scan_user
        sybase_use_ssh: true
        sybase_ssh_user: sybase_admin
        inspec_delegate_host: ""
