---
# Staging Inventory - Database Compliance Scanning
# For testing before production deployment

all:
  children:
    mssql_databases:
      hosts:
        # Add staging MSSQL servers
      vars:
        mssql_username: nist_scan_user

    oracle_databases:
      hosts:
        # Add staging Oracle databases
      vars:
        oracle_username: nist_scan_user

    sybase_databases:
      hosts:
        # Add staging Sybase databases
      vars:
        sybase_username: nist_scan_user
        sybase_use_ssh: true
        sybase_ssh_user: oracle
