---
# Staging Inventory - Database Compliance Scanning
# Host metadata only - credentials provided by AAP2

all:
  children:
    mssql_databases:
      hosts:
        # Add staging MSSQL servers here

    oracle_databases:
      hosts:
        # Add staging Oracle databases here

    sybase_databases:
      hosts:
        # Add staging Sybase databases here
