---
# Production Inventory - Database Compliance Scanning
# Credentials injected by AAP2 Custom Credential at runtime

all:
  # Delegate host (only needed for delegate mode)
  # Uncomment if InSpec runs on a remote bastion/jump server
  # hosts:
  #   inspec-runner:
  #     ansible_host: jumphost.example.com
  #     ansible_connection: ssh
  #     ansible_user: ansible_svc
  #     ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"

  children:
    # MSSQL Databases
    mssql_databases:
      hosts:
        # Example: Add your MSSQL servers here
        # SQLPROD01_1433:
        #   mssql_server: sqlprod01.example.com
        #   mssql_port: 1433
        #   mssql_version: "2019"
      vars:
        mssql_username: nist_scan_user
        # mssql_password: injected by AAP2 Custom Credential
        inspec_delegate_host: ""  # Empty = run on target host
        inspec_results_dir: /tmp/inspec_mssql_results
        inspec_debug_mode: false
        generate_summary_report: true

    # Oracle Databases
    oracle_databases:
      hosts:
        # Example: Add your Oracle servers here
        # ORAPROD01_1521:
        #   oracle_server: oraprod01.example.com
        #   oracle_port: 1521
        #   oracle_service: ORCL
        #   oracle_version: "19"
      vars:
        oracle_username: nist_scan_user
        # oracle_password: injected by AAP2 Custom Credential
        inspec_delegate_host: ""

    # Sybase Databases
    sybase_databases:
      hosts:
        # Example: Add your Sybase servers here
        # SYBPROD01_5000:
        #   sybase_server: sybprod01.example.com
        #   sybase_port: 5000
        #   sybase_version: "16"
      vars:
        sybase_username: nist_scan_user
        sybase_use_ssh: true
        sybase_ssh_user: sybase_admin
        # sybase_password: injected by AAP2 Custom Credential
        inspec_delegate_host: ""
