---
# Production Inventory - Database Compliance Scanning
# Credentials injected by AAP2 via extra vars

all:
  #############################################################################
  # OPTIONAL: Remote Delegate Host (only if NOT using local execution)
  # Uncomment if InSpec needs to run on a specific server (e.g., has sqlcmd)
  #############################################################################
  # hosts:
  #   inspec-runner:
  #     ansible_host: delegate.example.com
  #     ansible_connection: ssh
  #     ansible_user: ansible_svc
  #     # AAP2 machine credential injects ansible_password automatically
  #     # For local testing: ansible_password: "{{ vault_delegate_password }}"

  children:
    #############################################################################
    # MSSQL Databases
    #############################################################################
    mssql_databases:
      hosts:
        # Example hosts - replace with actual servers
        # sqlserver01_1433:
        #   mssql_server: sqlserver01.example.com
        #   mssql_port: 1433
        #   mssql_version: "2019"
        #   database_platform: mssql
        # sqlserver02_1433:
        #   mssql_server: sqlserver02.example.com
        #   mssql_port: 1433
        #   mssql_version: "2017"
        #   database_platform: mssql
      vars:
        mssql_username: nist_scan_user
        # mssql_password: injected by AAP2
        # inspec_delegate_host: "localhost"  # Default - runs on AAP2 execution node
        # inspec_delegate_host: "inspec-runner"  # Uncomment for remote delegate

    #############################################################################
    # Oracle Databases
    #############################################################################
    oracle_databases:
      hosts:
        # oracledb01_1521:
        #   oracle_server: oracledb01.example.com
        #   oracle_database: ORCL
        #   oracle_service: ORCL
        #   oracle_port: 1521
        #   oracle_version: "19"
        #   database_platform: oracle
      vars:
        oracle_username: nist_scan_user
        # oracle_password: injected by AAP2

    #############################################################################
    # Sybase Databases
    #############################################################################
    sybase_databases:
      hosts:
        # sybasedb01_5000:
        #   sybase_server: sybasedb01.example.com
        #   sybase_database: master
        #   sybase_port: 5000
        #   sybase_version: "16"
        #   database_platform: sybase
      vars:
        sybase_username: nist_scan_user
        sybase_use_ssh: true
        sybase_ssh_user: oracle
        # sybase_password: injected by AAP2
        # sybase_ssh_password: injected by AAP2
