---
# Unified Test Inventory - All Database Types
# ============================================
# This inventory includes MSSQL, Oracle, and Sybase databases
# for both localhost and delegate execution modes.
#
# Usage:
#   ansible-playbook -i inventories/hosts.yml test_playbooks/run_all_compliance.yml
#
# Required Environment Variables:
#   export MSSQL_PASSWORD='your_mssql_password'
#   export ORACLE_PASSWORD='your_oracle_password'
#   export SYBASE_PASSWORD='your_sybase_password'

all:
  vars:
    # Common InSpec settings
    base_results_dir: /tmp/compliance_scans
    inspec_debug_mode: true
    inspec_command_timeout: 1800
    generate_summary_report: true

  children:
    # =========================================
    # DELEGATE HOSTS (InSpec Runner VMs)
    # =========================================
    delegate_hosts:
      hosts:
        inspec-runner:
          ansible_host: 40.114.45.75
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/inspec_azure
          ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null"

    # =========================================
    # MSSQL DATABASES
    # =========================================
    mssql_databases:
      hosts:
        # Linux Container MSSQL (direct connection)
        mssql_test_01:
          mssql_server: 10.0.2.4
          mssql_port: 1433
          mssql_version: "2019"
          mssql_username: sa
          mssql_password: "{{ lookup('env', 'MSSQL_PASSWORD') | default('TestPass123', true) }}"
          mssql_database: master
          database_platform: mssql
          # Direct connection mode (no WinRM)
          use_winrm: false

        # Windows SQL Server (WinRM connection)
        mssql_windows_01:
          # SQL Server runs locally on Windows VM
          mssql_server: localhost
          mssql_port: 1433
          mssql_version: "2019"
          mssql_username: sa
          mssql_password: "{{ lookup('env', 'MSSQL_PASSWORD') }}"
          mssql_database: master
          database_platform: mssql
          # WinRM connection settings
          use_winrm: true
          winrm_host: "{{ lookup('env', 'WINDOWS_MSSQL_IP') | default('10.0.1.5', true) }}"
          winrm_port: 5985
          winrm_username: "{{ lookup('env', 'WINDOWS_ADMIN_USERNAME') | default('azureadmin', true) }}"
          winrm_password: "{{ lookup('env', 'WINDOWS_ADMIN_PASSWORD') }}"
          winrm_ssl: false
          # WinRM tests must run from the delegate host (Linux runner with train-winrm)
          inspec_delegate_host: inspec-runner
      vars:
        # Local connection - database hosts are metadata holders
        ansible_connection: local
        # Localhost mode: InSpec runs on this machine
        inspec_delegate_host: localhost
        inspec_results_dir: /tmp/compliance_scans/mssql

    # =========================================
    # ORACLE DATABASES
    # =========================================
    oracle_databases:
      hosts:
        oracle_test_01:
          oracle_server: 10.0.2.6
          oracle_port: 1521
          oracle_service: ORCLCDB
          oracle_database: ORCLCDB
          oracle_version: "19c"
          oracle_username: system
          oracle_password: "{{ lookup('env', 'ORACLE_PASSWORD') | default('OraclePass123', true) }}"
          database_platform: oracle
      vars:
        # Local connection - database hosts are metadata holders
        ansible_connection: local
        # Localhost mode: InSpec runs on this machine
        inspec_delegate_host: localhost
        inspec_results_dir: /tmp/compliance_scans/oracle

    # =========================================
    # SYBASE DATABASES
    # =========================================
    sybase_databases:
      hosts:
        sybase_test_01:
          sybase_server: 10.0.2.5
          sybase_port: 5000
          sybase_service: MYSYBASE
          sybase_database: master
          sybase_version: "16"
          sybase_username: sa
          sybase_password: "{{ lookup('env', 'SYBASE_PASSWORD') | default('myPassword', true) }}"
          database_platform: sybase
          # Sybase uses sybase_session (direct mode) - no SSH tunneling needed
          sybase_use_ssh: false
      vars:
        # Local connection - database hosts are metadata holders
        ansible_connection: local
        # Localhost mode: InSpec runs on this machine
        inspec_delegate_host: localhost
        inspec_results_dir: /tmp/compliance_scans/sybase

    # =========================================
    # GROUPED TARGETS FOR PLAYBOOKS
    # =========================================
    all_databases:
      children:
        mssql_databases:
        oracle_databases:
        sybase_databases:
